name: llm_contracts
channels:
  #- pytorch
  - conda-forge
  - defaults
dependencies:
  - conda-forge::cvxpy
  # common
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - nodejs>=12.0
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-xdist
  - python=3.11.7
  - scikit-learn
  - scipy
  - tqdm
  - selenium
  - plotly
  - mpltern
  - pip:
    - nbmerge

  #- pytorch=1.10.1
  #- mkl<2022 # prevents crash when importing torch on M1 mac via rosetta2
  #- cudatoolkit
  #- torchvision
  #- torchtext
